#!/bin/sh

picom --experimental-backends &
pulseaudio &
fcitx5 &
clipmenud  &
dunst &
xrdb merge ~/.config/x11/Xresources_catppuccin &
feh --bg-fill --no-fehbg ~/personal/pictures/wall.png &
xbanish -t 2 -s &
# run bar script and dwm ( do not remove this )
~/workspace/suckless/dwm/scripts/bar.sh &
dwm
